import { jsPDF } from 'jspdf';
import QRCode from 'qrcode';
import { APP_NAME, STATUS_LABEL, TAGLINE, pdfMoney as money } from './format';

// RentSlate brand colours (brand-600 / brand-800 / brand-50, gold-600).
export const TEAL = [13, 148, 136];
export const TEAL_DARK = [17, 94, 89];
export const TEAL_TINT = [240, 253, 250];
const INK = [28, 26, 22];
const MUTED = [98, 92, 83];
const RULE = [206, 197, 183];

const date = v => v ? new Date(v).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';
const reading = n => Number(n || 0).toFixed(3);
const addDays = (d, n) => { const x = new Date(d); x.setDate(x.getDate() + Number(n || 0)); return x; };

/** Shared letterhead: property on the left, RentSlate Meter wordmark on the right, teal rule. */
export function drawLetterhead(doc, { title, subtitle, address }) {
  const left = 12, right = 198;
  doc.setTextColor(...INK); doc.setFont('helvetica', 'bold'); doc.setFontSize(16); doc.text(title || 'Electricity Bill', left, 17);
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(...MUTED);
  if (subtitle) doc.text(subtitle, left, 23);
  if (address) doc.text(doc.splitTextToSize(address, 110), left, 28);
  doc.setFont('helvetica', 'bold'); doc.setFontSize(12); doc.setTextColor(...TEAL_DARK); doc.text(APP_NAME, right, 17, { align: 'right' });
  doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5); doc.setTextColor(...MUTED); doc.text(TAGLINE, right, 22, { align: 'right' });
  doc.setDrawColor(...TEAL); doc.setLineWidth(.8); doc.line(left, 34, right, 34);
  doc.setLineWidth(.2); doc.setTextColor(...INK);
  return 40;
}

export function drawFooter(doc, text) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setDrawColor(...RULE); doc.line(12, 284, 198, 284);
    doc.setFont('helvetica', 'normal'); doc.setFontSize(7); doc.setTextColor(...MUTED);
    doc.text(text || 'Generated by ' + APP_NAME + ' · ' + TAGLINE, 12, 289);
    doc.text('Page ' + i + ' of ' + pages, 198, 289, { align: 'right' });
  }
}

export async function createBillPdf(bill, ctx, portalUrl) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const left = 12, width = 186;
  const qr = await QRCode.toDataURL(portalUrl, { width: 240, margin: 1, errorCorrectionLevel: 'H' });

  const box = (x, y, w, h, fill = false) => {
    doc.setDrawColor(...RULE); doc.setLineWidth(.3);
    if (fill) { doc.setFillColor(...TEAL_TINT); doc.roundedRect(x, y, w, h, 3, 3, 'FD'); } else doc.roundedRect(x, y, w, h, 3, 3, 'S');
  };
  const label = (x, y, a, b) => {
    doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5); doc.setTextColor(...MUTED); doc.text(a, x, y);
    doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.setTextColor(...INK); doc.text(String(b ?? '—'), x, y + 5, { maxWidth: 58 });
  };
  const title = (text, y) => { doc.setFont('helvetica', 'bold'); doc.setFontSize(12); doc.setTextColor(...TEAL_DARK); doc.text(text, left, y); doc.setTextColor(...INK); };
  const table = (x, y, w, rows, headers) => {
    const cols = headers.length, cw = w / cols, rh = 8;
    doc.setFillColor(...TEAL_TINT); doc.rect(x, y, w, rh, 'F');
    doc.setFont('helvetica', 'bold'); doc.setFontSize(7.5); doc.setTextColor(...TEAL_DARK);
    headers.forEach((h, i) => doc.text(h, x + i * cw + 2, y + 5.3));
    doc.setTextColor(...INK); doc.setDrawColor(...RULE);
    let yy = y + rh;
    rows.forEach(row => {
      doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5);
      row.forEach((v, i) => doc.text(String(v ?? '—'), x + i * cw + 2, yy + 5.3, { maxWidth: cw - 3 }));
      doc.line(x, yy, x + w, yy);
      for (let i = 1; i < cols; i++) doc.line(x + i * cw, yy, x + i * cw, yy + rh);
      yy += rh;
    });
    doc.rect(x, y, w, yy - y);
    return yy;
  };

  let y = drawLetterhead(doc, { title: ctx.property?.name || 'Electricity Bill', subtitle: 'Electricity Bill cum Notice', address: ctx.property?.address });

  // Bill meta strip
  box(left, y, width, 15, true);
  label(16, y + 5, 'Bill No.', bill.bill_number);
  label(66, y + 5, 'Bill Date', date(bill.bill_date));
  label(112, y + 5, 'Due Date', ctx.dueDays != null ? date(addDays(bill.bill_date, ctx.dueDays)) : '—');
  label(158, y + 5, 'Status', STATUS_LABEL[bill.status] || bill.status);
  y += 20;

  // Account block
  box(left, y, width, 32);
  label(16, y + 7, 'Account / Meter', `${ctx.meter?.code || '—'} / ${ctx.meter?.number || '—'}`);
  label(82, y + 7, 'Tenant', ctx.tenant?.name || 'Vacant');
  label(144, y + 7, 'Room', ctx.room?.room_number || '—');
  label(16, y + 21, 'Floor', ctx.room?.floor || '—');
  label(82, y + 21, 'Unit', 'kWh');
  label(144, y + 21, 'Reading Date', date(bill.reading_date));
  y += 42;

  title('Billing Summary', y);
  const rows = [
    ['Previous Reading', reading(bill.previous_reading)],
    ['Current Reading', reading(bill.current_reading)],
    ['Consumption', `${reading(bill.units)} kWh`],
    ['Rate', money(bill.rate_per_unit) + ' / kWh'],
    ['Energy Charges', money(bill.energy_charge)],
  ];
  if (Number(bill.fixed_charge)) rows.push(['Fixed Charges', money(bill.fixed_charge)]);
  if (Number(bill.other_charge)) rows.push(['Other Charges', money(bill.other_charge)]);
  if (Number(bill.tax_amount)) rows.push(['Tax', money(bill.tax_amount)]);
  rows.push(['Total Payable', money(bill.total_amount)]);
  const tableEnd = table(left, y + 4, 130, rows, ['Description', 'Amount / Value']);

  // Total + QR panel
  const py = y + 4;
  box(148, py, 50, 76, true);
  doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5); doc.setTextColor(...MUTED); doc.text('TOTAL PAYABLE', 152, py + 8);
  doc.setFont('helvetica', 'bold'); doc.setFontSize(15); doc.setTextColor(...TEAL_DARK); doc.text(money(bill.total_amount), 152, py + 17);
  doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5); doc.setTextColor(...MUTED); doc.text('Bill generated by', 152, py + 26);
  doc.setFont('helvetica', 'bold'); doc.setTextColor(...INK); doc.text(bill.source === 'OWNER' ? 'Owner' : 'Tenant (owner approved)', 152, py + 31);
  doc.addImage(qr, 'PNG', 158, py + 36, 30, 30);
  doc.setFont('helvetica', 'normal'); doc.setFontSize(6.5); doc.setTextColor(...MUTED); doc.text('Scan for your live account', 173, py + 71, { align: 'center' });
  y = Math.max(tableEnd, py + 76) + 10;

  title('Important Information', y);
  doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5); doc.setTextColor(...INK);
  [
    '1. Consumption is calculated in kWh as current approved reading minus the last paid reading.',
    '2. A tenant-submitted bill remains pending until reviewed and approved by the owner.',
    '3. Only approved bills are available for tenant PDF download.',
    '4. Owner-generated bills are finalized immediately according to the configured billing rate.',
    '5. This document is a property-managed electricity bill and is not an official utility-company bill.',
  ].forEach((t, i) => doc.text(t, 16, y + 7 + i * 5));

  // Page 2
  doc.addPage();
  y = drawLetterhead(doc, { title: 'Meter & Payment Details', subtitle: `Bill ${bill.bill_number} · ${ctx.meter?.code || ''}`, address: ctx.property?.name });
  title('Meter Reading Details', y);
  y = table(left, y + 4, width, [[
    ctx.meter?.number || '—', 'kWh', ctx.previousDate ? date(ctx.previousDate) : '—', reading(bill.previous_reading), date(bill.reading_date), reading(bill.current_reading), reading(bill.units), '1', 'OK',
  ]], ['Meter', 'Unit', 'Prev. Date', 'Prev. Read', 'Curr. Date', 'Curr. Read', 'Diff.', 'M.F.', 'Remark']) + 10;

  title('Last Six Bills', y);
  const six = (ctx.history || []).slice(0, 6).map((b, i) => [String(i + 1), date(b.bill_date), reading(b.units) + ' kWh', money(b.total_amount), STATUS_LABEL[b.status] || b.status]);
  y = table(left, y + 4, width, six.length ? six : [['—', '—', '—', '—', '—']], ['#', 'Bill Date', 'Units', 'Amount', 'Status']) + 10;

  title('Last Payment Details', y);
  const lp = ctx.lastPayment;
  y = table(left, y + 4, width, [[lp ? date(lp.payment_date) : '—', lp ? money(lp.amount) : '—', lp?.payment_mode || '—', lp?.receipt_no || '—']], ['Payment Date', 'Payment Amount', 'Payment Mode', 'Receipt No.']) + 10;

  const notes = doc.splitTextToSize(bill.notes || 'This bill is generated and maintained by the property owner. The QR code opens the current meter account portal.', 176);
  const notesH = 12 + notes.length * 3.6;
  box(left, y, width, notesH);
  doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.setTextColor(...TEAL_DARK); doc.text('Bill Notes', 16, y + 7);
  doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5); doc.setTextColor(...INK); doc.text(notes, 16, y + 12);

  drawFooter(doc);
  return doc.output('blob');
}

export function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
