import { jsPDF } from 'jspdf';
import QRCode from 'qrcode';

const money = n => `₹${Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})`;
const date = v => v ? new Date(v).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}) : '—';

export async function createBillPdf(bill, ctx, portalUrl){
  const doc = new jsPDF({unit:'mm',format:'a4'});
  const W=210, left=12, right=198;
  const qr=await QRCode.toDataURL(portalUrl,{width:240,margin:1,errorCorrectionLevel:'H'});

  const box=(x,y,w,h,fill='')=>{doc.setDrawColor(80);doc.setLineWidth(.3);if(fill){doc.setFillColor(248,250,252);doc.roundedRect(x,y,w,h,3,3,'FD')}else doc.roundedRect(x,y,w,h,3,3,'S')};
  const line=(y)=>{doc.setDrawColor(170);doc.line(left,y,right,y)};
  const label=(x,y,a,b)=>{doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(90);doc.text(a,x,y);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.setTextColor(25);doc.text(String(b??'—'),x,y+5)};
  const title=(text,y)=>{doc.setFont('helvetica','bold');doc.setFontSize(13);doc.setTextColor(20);doc.text(text,left,y)};
  const table=(x,y,width,rows,headers)=>{
    const cols=headers.length, cw=width/cols, rh=8;
    doc.setFillColor(231,241,247);doc.rect(x,y,width,rh,'F');doc.setFont('helvetica','bold');doc.setFontSize(7);
    headers.forEach((h,i)=>doc.text(h,x+i*cw+2,y+5));
    let yy=y+rh;
    rows.forEach(row=>{doc.setFont('helvetica','normal');doc.setFontSize(7);row.forEach((v,i)=>doc.text(String(v??'—'),x+i*cw+2,yy+5));doc.setDrawColor(210);doc.rect(x,yy,width,rh);for(let i=1;i<cols;i++)doc.line(x+i*cw,yy,x+i*cw,yy+rh);yy+=rh});
    doc.rect(x,y,width,yy-y);return yy;
  };

  doc.setFont('helvetica','bold');doc.setFontSize(16);doc.text(ctx.property?.name||'Electricity Bill',left,17);
  doc.setFontSize(8);doc.setFont('helvetica','normal');doc.text('Electricity Bill Cum Notice',left,23);
  doc.text(ctx.property?.address||'',left,28);
  doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text(`Bill No: ${bill.bill_number}`,128,17);
  doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text(`Bill Date: ${date(bill.bill_date)}`,128,23);
  doc.text(`Status: ${bill.status}`,128,28);
  line(32);

  box(left,36,186,40);
  label(16,43,'Account / Meter',`${ctx.meter?.code||'—'} / ${ctx.meter?.number||'—'}`);
  label(82,43,'Tenant',ctx.tenant?.name||'Vacant');
  label(144,43,'Room',ctx.room?.room_number||'—');
  label(16,59,'Floor',ctx.room?.floor||'—');
  label(82,59,'Unit', 'kWh');
  label(144,59,'Reading Date',date(bill.reading_date));

  title('Billing Summary',85);
  table(left,89,130,[
    ['Previous Reading',Number(bill.previous_reading||0).toFixed(3)],
    ['Current Reading',Number(bill.current_reading||0).toFixed(3)],
    ['Consumption',`${Number(bill.units||0).toFixed(3)} units`],
    ['Rate',money(bill.rate_per_unit)+' / kWh'],
    ['Energy Charges',money(bill.energy_charge)]
  ],['Description','Amount / Value']);

  box(150,89,48,64,'#f8fafc');
  doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(80);doc.text('TOTAL PAYABLE',154,98);
  doc.setFont('helvetica','bold');doc.setFontSize(16);doc.setTextColor(15);doc.text(money(bill.total_amount),154,110);
  doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(80);doc.text('Bill generated by',154,124);doc.setFont('helvetica','bold');doc.setTextColor(20);doc.text(bill.source==='OWNER'?'Owner':'Tenant',154,129);
  doc.addImage(qr,'PNG',157,136,30,30);doc.setFont('helvetica','normal');doc.setFontSize(6);doc.text('Scan for live account',154,169);

  title('Calculation Details',163);
  table(left,167,186,[
    ['Energy Charges',money(bill.energy_charge)],
    ['Total Payable',money(bill.total_amount)]
  ],['Charge','Amount']);

  doc.addPage();
  doc.setFont('helvetica','bold');doc.setFontSize(14);doc.text('Meter & Payment Details',left,17);
  title('Meter Reading Details',25);
  table(left,29,186,[[
    ctx.meter?.number||'—','kWh',date(bill.reading_date),Number(bill.previous_reading||0).toFixed(3),date(bill.bill_date),Number(bill.current_reading||0).toFixed(3),Number(bill.units||0).toFixed(3),'1','OK'
  ]],['Meter','Unit','Prev. Date','Prev. Read','Current Date','Current Read','Diff.','M.F.','Remark']);

  title('Last Six Months Consumption',48);
  const six=(ctx.history||[]).slice(0,6).map((b,i)=>[
    String(i+1),date(b.bill_date).slice(3),Number(b.units||0).toFixed(3)+' kWh',money(b.total_amount),b.status
  ]);
  table(left,52,186,six.length?six:[['—','—','—','—','—']],['#','Bill Month','Units','Amount','Status']);

  title('Last Payment Details',108);
  const lp=ctx.lastPayment;
  table(left,112,186,[[
    lp?date(lp.payment_date):'—',lp?money(lp.amount):'—',lp?.payment_mode||'—',lp?.receipt_no||'—'
  ]],['Payment Date','Payment Amount','Payment Mode','Receipt No.']);

  box(left,131,186,36);
  doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text('Bill Notes',16,140);
  doc.setFont('helvetica','normal');doc.setFontSize(7);
  const notes=doc.splitTextToSize(bill.notes||'This bill is generated and maintained by the property owner. The access code opens the current meter account portal.',178);
  doc.text(notes,16,147);

  title('Important Information',177);
  doc.setFont('helvetica','normal');doc.setFontSize(7);
  const info=[
    '1. Consumption is calculated in kWh as current approved reading minus the last paid reading.',
    '2. A tenant-submitted bill remains pending until reviewed and approved by the owner.',
    '3. Only approved bills are available for tenant PDF download.',
    '4. Owner-generated bills are finalized immediately according to the configured billing rate and charges.',
    '5. This document is a property-managed electricity bill and is not an official utility-company bill.'
  ];
  info.forEach((t,i)=>doc.text(t,16,184+i*5));
  doc.setFontSize(6);doc.setTextColor(100);doc.text('Generated by Electricity Bill Manager',left,207);
  return doc.output('blob');
}

export function downloadBlob(blob, filename){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
